notification:
  sms_providers:
    aws_sns:
      enabled: '%env(bool:AWS_SNS_ENABLED)%'
      api_key: '%env(AWS_SNS_API_KEY)%'
      api_secret: '%env(AWS_SNS_API_SECRET)%'
    twilio:
      enabled: '%env(bool:TWILIO_ENABLED)%'
      account_sid: '%env(TWILIO_ACCOUNT_SID)%'
      auth_token: '%env(TWILIO_AUTH_TOKEN)%'
  email_providers:
    aws_ses:
      enabled: '%env(bool:AWS_SES_ENABLED)%'
      api_key: '%env(AWS_SES_API_KEY)%'
      api_secret: '%env(AWS_SES_API_SECRET)%'
    smtp:
      enabled: '%env(bool:SMTP_ENABLED)%'
      host: '%env(SMTP_HOST)%'
      port: '%env(int:SMTP_PORT)%'
      username: '%env(SMTP_USERNAME)%'
      password: '%env(SMTP_PASSWORD)%'
      encryption: '%env(SMTP_ENCRYPTION)%'
  push_notification_providers:
    pushy:
      enabled: '%env(bool:PUSHY_ENABLED)%'
      api_key: '%env(PUSHY_API_KEY)%'