# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\NotificationService:
        arguments:
            $providerFactory: '@App\Service\Factory\ProviderFactory'
            $failover: '%env(bool:NOTIFICATION_FAILOVER)%'
            $maxAttempts: '%env(int:NOTIFICATION_MAX_ATTEMPTS)%'
            $throttlingEnabled: '%env(bool:NOTIFICATION_THROTTLING_ENABLED)%'
            $throttlingLimit: '%env(int:NOTIFICATION_THROTTLING_LIMIT)%'
            $throttlingPeriod: '%env(int:NOTIFICATION_THROTTLING_PERIOD)%'
            $trackingEnabled: '%env(bool:NOTIFICATION_TRACKING_ENABLED)%'
    # SMS Providers
    App\Service\Provider\AwsSnsProvider:
        arguments:
            $apiKey: '%env(AWS_SNS_API_KEY)%'
            $apiSecret: '%env(AWS_SNS_API_SECRET)%'
        tags: ['sms_provider']

    App\Service\Provider\TwilioProvider:
        arguments:
            $accountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(TWILIO_AUTH_TOKEN)%'
        tags: ['sms_provider']

    # Email Providers
    App\Service\Provider\AwsSesProvider:
        arguments:
            $apiKey: '%env(AWS_SES_API_KEY)%'
            $apiSecret: '%env(AWS_SES_API_SECRET)%'
        tags: ['email_provider']

    App\Service\Provider\SmtpProvider:
        arguments:
            $mailer: '@mailer'
            $host: '%env(SMTP_HOST)%'
            $port: '%env(int:SMTP_PORT)%'
            $username: '%env(SMTP_USERNAME)%'
            $password: '%env(SMTP_PASSWORD)%'
            $encryption: '%env(SMTP_ENCRYPTION)%'
        tags: ['email_provider']

    # Push Notification Providers
    App\Service\Provider\PushyProvider:
        arguments:
            $apiKey: '%env(PUSHY_API_KEY)%'
        tags: ['push_notification_provider']

    #All Provider Factory
    app.sms_providers_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            - aws_sns: '@App\Service\Provider\AwsSnsProvider'
              twilio: '@App\Service\Provider\TwilioProvider'

    app.email_providers_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            - aws_ses: '@App\Service\Provider\AwsSesProvider'
              smtp: '@App\Service\Provider\SmtpProvider'

    app.push_notification_providers_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            - pushy: '@App\Service\Provider\PushyProvider'

    App\Service\Factory\ProviderFactory:
        arguments:
            $smsProviders: '@app.sms_providers_locator'
            $emailProviders: '@app.email_providers_locator'
            $pushNotificationProviders: '@app.push_notification_providers_locator'
            $smsProvidersConfig:
                aws_sns:
                    enabled: '%env(bool:AWS_SNS_ENABLED)%'
                twilio:
                    enabled: '%env(bool:TWILIO_ENABLED)%'
            $emailProvidersConfig:
                aws_ses:
                    enabled: '%env(bool:AWS_SES_ENABLED)%'
                smtp:
                    enabled: '%env(bool:SMTP_ENABLED)%'
            $pushNotificationProvidersConfig:
                pushy:
                    enabled: '%env(bool:PUSHY_ENABLED)%'

    App\Command\NotificationEmailSendCommand:
        arguments:
            $notificationService: '@App\Service\NotificationService'
        tags:
            - { name: 'console.command' }